# fly.toml app configuration file generated for contacthorse-docs on 2025-07-28T14:48:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contacthorse-docs'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
